# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: comments
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: comments
#   template:
#     metadata:
#       labels:
#         app: comments
#     spec:
#       containers:
#         - name: comments
#           image: mdrakibul/comments
#       ports:
#         - containerPort: 5001

apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-depl
  labels:
    app: comments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: mdrakibul/comments:latest
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: comments-srv
spec:
  type: ClusterIP
  selector:
    app: comments
  ports:
    - name: comments
      protocol: TCP
      port: 5002
      targetPort: 5002
