# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: event
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: event
#   template:
#     metadata:
#       labels:
#         app: event
#     spec:
#       containers:
#         - name: event
#           image: mdrakibul/event
#       ports:
#         - containerPort: 5001

apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-depl
  labels:
    app: event
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event
  template:
    metadata:
      labels:
        app: event
    spec:
      containers:
        - name: event
          image: mdrakibul/event-bus:latest
          ports:
            - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: event-srv
spec:
  type: ClusterIP
  selector:
    app: event
  ports:
    - name: event
      protocol: TCP
      port: 6000
      targetPort: 6000
