# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: posts
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: posts
#   template:
#     metadata:
#       labels:
#         app: posts
#     spec:
#       containers:
#         - name: posts
#           image: mdrakibul/posts
#       ports:
#         - containerPort: 5001

apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
  labels:
    app: posts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: mdrakibul/posts:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: NodePort
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 5000
      targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: posts-cluster-ip-srv
spec:
  type: ClusterIP
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 5000
      targetPort: 5000
