apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
  labels:
    app: query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: mdrakibul/query:latest
          resources:
              limits:
                memory: 512Mi
                cpu: "1"
              requests:
                memory: 256Mi
                cpu: "0.2"
          ports:
            - containerPort: 6001
---
apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  type: NodePort
  selector:
    app: query
  ports:
    - name: query
      protocol: TCP
      port: 6001
      targetPort: 6001

---
apiVersion: v1
kind: Service
metadata:
  name: query-cluster-ip-srv
spec:
  type: ClusterIP
  selector:
    app: query
  ports:
    - name: query
      protocol: TCP
      port: 6001
      targetPort: 6001
