apiVersion: v1
kind: Service
metadata:
  name: hello-nodejs-srv
spec:
  type: NodePort
  selector:
    app: hello-nodejs
  ports:
    - name: hello-nodejs
      protocol: TCP
      port: 5000
      targetPort: 5000
